# Generated by Django 5.1.6 on 2025-03-10 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="goals_against_team1",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Goals Against Team 1"
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="goals_against_team2",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Goals Against Team 2"
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="goals_for_team1",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Goals For Team 1"
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="goals_for_team2",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Goals For Team 2"
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="time_elapsed",
            field=models.CharField(
                blank=True,
                help_text='Current time elapsed in the game (e.g., "45+2", "90")',
                max_length=20,
                verbose_name="Time Elapsed",
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("pending_verification", "Pending Verification"),
                    ("verified", "Verified"),
                    ("disputed", "Disputed"),
                ],
                default="unverified",
                max_length=20,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="scoredetail",
            name="assisted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The player who provided the assist (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_assists",
                to="teams.player",
                verbose_name="Assisted By",
            ),
        ),
        migrations.AddField(
            model_name="scoredetail",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("goal", "Goal"),
                    ("assist", "Assist"),
                    ("own_goal", "Own Goal"),
                    ("penalty", "Penalty"),
                    ("free_kick", "Free Kick"),
                    ("basket", "Basket"),
                    ("point", "Point"),
                    ("other", "Other"),
                ],
                default="goal",
                help_text="Type of scoring event",
                max_length=20,
                verbose_name="Event Type",
            ),
        ),
        migrations.AddField(
            model_name="scoredetail",
            name="minute",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Minute of the game when the event occurred",
                null=True,
                verbose_name="Minute",
            ),
        ),
        migrations.AddField(
            model_name="scoredetail",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL to video clip of the scoring event",
                max_length=255,
                null=True,
                verbose_name="Video URL",
            ),
        ),
    ]
